### PR TITLE
mohammedarbaz119's card

### PR DESCRIPTION
**Pull request by mohammedarbaz119**

### CODE REVIEW

**Comment by nzaih1999** [comment]
Hello i noticed you have closed your PR. if you are having any issues ill be really glad to help you

**Comment by mohammedarbaz119** [comment]
> Hello i noticed you have closed your PR. if you are having any issues ill be really glad to help you

i am just adding my card but the spacing is changing the head of html so it is getting a conflict

**Comment by mohammedarbaz119** [comment]
> Hello i noticed you have closed your PR. if you are having any issues ill be really glad to help you

i will close this and try to create a new one

**Comment by mohammedarbaz119** [comment]
> Hello i noticed you have closed your PR. if you are having any issues ill be really glad to help you

thanks for asking

**Pull request closed without merging**
