### PR TITLE
Create Urdu.md

### PR DESCRIPTION
**Pull request by hichem-18**
Hi I added the urdu documentation

### CODE REVIEW

**Comment by ibrahimdevop21** [comment]
Hi @hichem-18,

Thanks for adding the Urdu documentation! A member of our team will review your contribution soon. In the meantime, please take a look at our contribution guide to make sure everything is in line with our guidelines.

Thanks again for your contribution! Feel free to ask if you have any questions.

Best,
@ibrahimdevop21

**Review by TenTraicion — CHANGES_REQUESTED** [review]
hello @hichem-18, Thanks for your contribution, but it has some major issue, that's why we can't merge it as of now.
- the file is in wrong direction, it should be in `/translation/readme/`
- the file is incomplete, most of the details are missing
- the links, image sources are missing
- the links in the table of contents are not working.

Kindly fix these and resubmit, and follow the guidelines in our translation doc properly. Thanks.

**Comment by hichem-18** [comment]
Hi @TenTraicion, I see thank you for you time. I will fix them and resubmit

**Comment by hichem-18** [comment]
@TenTraicion Hi! I've made all the requested changes. Please take a look when you have a chance.

**Review by TenTraicion — APPROVED** [review]

**Pull request merged**
