### PR TITLE
Mbedobe's-card

### PR DESCRIPTION
**Pull request by MBEDOBE**
I added my card to the index.html file

### CODE REVIEW

**Review by Preet-Sojitra — COMMENTED** [review]
@MBEDOBE It seems you have added your card at the end of the `index.html`. It would be great if your move this at the beginning of the file. In the beginning of the `index.html`, there is one comment "add your card below this line", below that line you have to add your card. So please move it upwards and then commit it and push , we will merge it.

**Comment by MBEDOBE** [comment]
> @MBEDOBE It seems you have added your card at the end of the `index.html`. It would be great if your move this at the beginning of the file. In the beginning of the `index.html`, there is one comment "add your card below this line", below that line you have to add your card. So please move it upwards and then commit it and push , we will merge it.

@Preet-Sojitra i have made the requested changes

**Comment by MBEDOBE** [comment]
@Preet-Sojitra i have made the requested changes

**Comment by Preet-Sojitra** [comment]
Congratulationss @MBEDOBE for your first contribution in open source. Your pull request has been merged. You can view your card on [project's website](https://syknapse.github.io/Contribute-To-This-Project/). All the best for your future open source journey. Hope you have learnt new things. 
Have a great day :)

**Pull request merged**
