### PR TITLE
Created my branch,

### PR DESCRIPTION
**Pull request by benjaminnkem**
Added my card
Correct some other people syntax errors that cause prettier to throw errors without editing anyone's content

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please include your name in your card's start and end comments. Also please do not change the rest of the file. In addition, you included changes to package-lock.json in your PR - why is that? Thx.

**Comment by CandidDeer** [comment]
@benjaminnkem Yes, I can see that. However, this doesn't answer my question about package-lock.json?

**Comment by benjaminnkem** [comment]
> @benjaminnkem Yes, I can see that. However, this doesn't answer my question about package-lock.json?

Ohhh, the name property was moved to the top of the package-lock.json file automatically, I'm thinking the prettier extension did it.

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@benjaminnkem, don't use any formatting style while creating a pr on our project, cause we already have prettier formatting.
Fixed your card. Kindly wait, one of us will merge your card soon.

@CandidDeer, it's all up to you now.

**Review by CandidDeer — APPROVED** [review]

**Comment by CandidDeer** [comment]
@TenTraicion Thank you for stepping in. I have merged the PR now. @benjaminnkem Your card will be live in a moment.

**Comment by benjaminnkem** [comment]
Okay, thanks alot 💜

**Pull request merged**
