### PR TITLE
saicharan's card

### PR DESCRIPTION
**Pull request by Saicharan0662**
Added my card to index.html file

### CODE REVIEW

**Comment by Saicharan0662** [comment]
I have resolved the conflicts, please let me know if any other issue is there. Hoping it merges soon.

**Comment by Preet-Sojitra** [comment]
@Saicharan0662 Your current pull request is causing more than 400 merge conflicts. So you are requested to add your card again and open a new pull request. Once you open new pull request, we will merge it.
Thank you :)

**Comment by win21H2** [comment]
Hello @Saicharan0662, could you please move your card past the template. Thanks!

**Comment by CandidDeer** [comment]
Hi Sai, since the only merge conflict was posed by your card position in the file, I've gone ahead and moved your card for you as suggested by win21H2. 👍🏻 All is well now and your contribution is live. Thank you for sharing your resources.

**Pull request merged**
