### PR TITLE
Add my card information

### PR DESCRIPTION
**Pull request by vishnu-mouli-102408**

### CODE REVIEW

**Review by CandidDeer — APPROVED** [review]

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Your PR is trying to make changes to package-lock.json. Please remove that part of your PR and we'll be good to merge. Thx.

**Comment by vishnu-mouli-102408** [comment]
> Your PR is trying to make changes to package-lock.json. Please remove that part of your PR and we'll be good to merge. Thx.

Can you please tell me how to do that?

**Comment by vishnu-mouli-102408** [comment]
> > Your PR is trying to make changes to package-lock.json. Please remove that part of your PR and we'll be good to merge. Thx.
> 
> Can you please tell me how to do that?

Please check one. I have done it.

**Comment by CandidDeer** [comment]
@vishnu-mouli-102408 You're still pushing package-lock.json. Please remove it from your PR. Thx.

**Comment by CandidDeer** [comment]
Please note that any PRs with unresolved change request will be closed 7 days after initial opening. Thx.

**Pull request closed without merging**
