### PR TITLE
Adding my recommendation card to the index.html

### PR DESCRIPTION
**Pull request by L4r4TW**
Added my recommendation card to the index.html, thank you for this awsome opportunity :)

### CODE REVIEW

**Comment by L4r4TW** [comment]
Added my card to index.html file

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please add the links(href) to your resources. Then I'll be happy to merge. Thx.

**Comment by L4r4TW** [comment]
How can I make my changes? Should I create a new branch, push it to my fork, and create a new pull request, or is there another way to do this?

**Comment by L4r4TW** [comment]
I made the requested changes

**Comment by CandidDeer** [comment]
Perfectly executed, thank you ✨ I have merged your PR and your card will be live in a moment.

**Comment by L4r4TW** [comment]
Thank you Lisa :))) I'm so happy now

**Pull request merged**
