### PR TITLE
Ritu singh card

### PR DESCRIPTION
**Pull request by RituSingh2002**
I have Added new Card Please Accept my contribution.

### CODE REVIEW

**Comment by Prajwalprakash3722** [comment]
Thank you for your contribution, there is a slight problem with your code, you have added your code at the middle of cards which would lead to generate your card in somewhere in the website, please move your card code just one line below the template. 👍🏼

**Review by iatharva — CHANGES_REQUESTED** [review]
Please move your card code to just one line below the template.

**Comment by iatharva** [comment]
My bad, We meant to paste your card below the card template i.e. after line no 78 (with 79th line left blank as space). 
Looks like you have pasted the card at the bottom of the file.

**Comment by iatharva** [comment]
Please refer to the above comment for the changes

**Comment by iatharva** [comment]
Looks good, Thank you for your contribution! Hope you have a good journey ahead in open-source 🙂

**Pull request merged**
