### PR TITLE
Tamrakar's card

### PR DESCRIPTION
**Pull request by Tamrakar182**
added my card to index.html file

### CODE REVIEW

**Review by TenTraicion — APPROVED** [review]

**Review by CandidDeer — APPROVED** [review]

**Comment by CandidDeer** [comment]
Thank you for your contribution. I have merged your PR and your card will be live in a moment.

**Comment by Tamrakar182** [comment]
thanks for adding my card 🙏🙏

**Comment by Tamrakar182** [comment]
should i delete this branch?

**Comment by CandidDeer** [comment]
@Tamrakar182 You may if you want, yes. 👍🏻

**Pull request merged**
