### PR TITLE
benortiz-card

### PR DESCRIPTION
**Pull request by Ben-Ortiz**
Added my card to index.html, tried this before but forgot about how to do it lol

### CODE REVIEW

**Review by iatharva — CHANGES_REQUESTED** [review]
Looks like you have added your card at the end of the file, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

**Comment by Ben-Ortiz** [comment]
I've fixed the placement of my card to be right below the template. Do I have to worry about the merge conflicts as well?

**Comment by iatharva** [comment]
No, don't worry we will resolve the conflicts.

**Review by iatharva — APPROVED** [review]

**Comment by Ben-Ortiz** [comment]
Thanks!

**Comment by iatharva** [comment]
Thanks a lot for the contribution, Hope you have great journey ahead in open source :)

**Pull request merged**
