### PR TITLE
Fixed prettier for html

### PR DESCRIPTION
**Pull request by StepanNaryshkov**
Prettier did not work because of the invalid index.html file.
All issues are fixed and prettier should work well for the new PRs.
image

image
image

This PR was created within Hacktoberfest. thx

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse Can you please check and approve if I can merge this? Sounds like a great contribution, if it fixes the Prettier issue!

**Comment by StepanNaryshkov** [comment]
if you can merge it before other PRs it will be great, because I need to resolve conflicts after each merge/updates in index.html :)

**Review by Syknapse — APPROVED** [review]
Thank you for a useful contribution. I will merge it now

**Comment by Syknapse** [comment]
A tip for my fellow maintainers, if you run `npm run prettier-html` in the terminal (in the project directory), prettier will always show you errors like these that you can fix and commit to make sure prettier works again. Thanks @StepanNaryshkov for the help with this

**Pull request merged**
