### PR TITLE
clean some code  and make some improvement in the design

### PR DESCRIPTION
**Pull request by grixxxx**

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse Please check these general enhancements for feasability to merge. Thx!

**Comment by grixxxx** [comment]
> m

what's the update?

**Comment by grixxxx** [comment]
> @Syknapse Please check these general enhancements for feasability to merge. Thx!
what's the update?

**Comment by Syknapse** [comment]
hi @grixxxx I will check the style changes you have submitted shortly and let you know.
But I have also noticed that you installed Parcel on the project. Can you explain please why you think this is useful for this project and what improvements it will provide for our users (contributors)?

**Comment by grixxxx** [comment]
> hi @grixxxx I will check the style changes you have submitted shortly and let you know. But I have also noticed that you installed Parcel on the project. Can you explain please why you think this is useful for this project and what improvements it will provide for our users (contributors)?

hello. i used to create project with parcel 'cause to make all dependencies files will convert into javascript files so that files will make it shrink. and for better production too.

**Comment by Syknapse** [comment]
I understand @grixxxx, however this is not really relevant to this project because we don't deploy a build to a production server, instead we're simply using GitHub's own pages to display our web, which is made up of simple html and JS files. So I can't see that this adds anything useful to the project. Thanks for trying it though, but if you can please uninstall it, remove the dist folder and everything else related to it and commit so that we're left only with the design changes so I can review them and merge them for you. 

Thanks

**Comment by grixxxx** [comment]
> 

okay sir

**Comment by TenTraicion** [comment]
@grixxxx as this PR is 7 days or more old and no changes made since 7 or more days, I am closing this PR.
You are welcome to create another PR. 

for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

**Pull request closed without merging**
