### PR TITLE
Contributing card regarding AriZeto.

### PR DESCRIPTION
**Pull request by AriZeto**
Added information regarding AriZeto to this open source contribution.

### CODE REVIEW

**Comment by AriZeto** [comment]
Hi there, a bit confused as to what happened overnight.

Initially, this branch had no conflicts. It just needed approval to be merged into main. However, as of this morning, there appears to be a conflict - and for some reason, someone else's information is within mine.

**Comment by theAravinthM** [comment]
Hi @AriZeto No Worries :)
Your PR has been conflicted with the other contributor. It is of no one's mistake. 

We will resolve this as soon as possible from our end.

**Comment by AriZeto** [comment]
> Hi @AriZeto No Worries :) Your PR has been conflicted with the other contributor. It is of no one's mistake.
> 
> We will resolve this as soon as possible from our end.

Great, thank you. Is there any additional things I need to do?

**Comment by theAravinthM** [comment]
Nope. We will proceed your PR from our end! Thanks for you patience!

**Comment by theAravinthM** [comment]
Congratulations @AriZeto on your PR Merge, and Thanks for your Contribution! Your card will be live on our Website in a moment!

Now you can follow the Next Steps. You are also welcome to join our Discord Server: https://discord.gg/tWkvS4ueVF and be a part of our community.

Happy contributing!

**Pull request merged**
