### PR TITLE
adding my card information to index.html

### PR DESCRIPTION
**Pull request by benharrimohamed**
Added a new card and modify the content

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please move your card up to start in line 117 and change the start and end comment to include your name instead of jDaowy. Thx.

**Review by benharrimohamed — COMMENTED** [review]
make some changes

**Comment by CandidDeer** [comment]
@benharrimohamed Your card still starts in line 2000-something. Please move it up to start in line 117. Thx.

**Comment by CandidDeer** [comment]
@benharrimohamed Please note that we will be closing any PRs 7 days after initial opening if requested changes have not been resolved by then. Thx.

**Pull request closed without merging**
