### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by txlan1710**

### CODE REVIEW

**Comment by ascodeasice** [comment]
Hi, this PR is copy and paste of part of of the file, can you explain the purpose of this PR? (why change it, or what is does), Thanks

**Comment by txlan1710** [comment]
@ascodeasice  I have an error in the file ".github/workflows/.travis.yml". The error it shows is "The requested URL returned error: 403 Error: Process completed with exit code 128". I don't know what to do

**Comment by ascodeasice** [comment]
Are you talking about the CI in your previous PR? If so, that is normal, you don't need to worry about it

**Comment by ascodeasice** [comment]
I'm closing this PR if there's no problem, thanks

**Pull request closed without merging**
