### PR TITLE
Added Kushal's Card .

### PR DESCRIPTION
**Pull request by Kushal997-das**
contribute (3)

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@Syknapse Please check .

**Comment by Syknapse** [comment]
> @Syknapse Please check .

Oh hi, sorry I think I didn´t explain well. Your PRhas already been merged. If you go to the [website](https://syknapse.github.io/Contribute-To-This-Project/) you will see that your card is already deployed there.

**Comment by Syknapse** [comment]
Closing this PR now as it has already been merged

**Comment by Kushal997-das** [comment]
Thanks @Syknapse

**Pull request closed without merging**
