### PR TITLE
Added my card information

### PR DESCRIPTION
**Pull request by David-Thapa**

### CODE REVIEW

**Comment by sanilborkar** [comment]
Hi David! I can see that your PR has **15,918 additions and 17,834 deletions**. This can arise from your IDE modifying the indentations as per your local IDE settings.

Please remove all indentations related and other extraneous changes and update this PR. Once done, I will be able to merge it. Feel free to reach out to us if you have any questions.

Thank you.

**Review by sanilborkar — CHANGES_REQUESTED** [review]
Hi @David-Thapa ! I can see that your PR has 15,918 additions and 17,834 deletions. This can arise from your IDE modifying the indentations as per your local IDE settings.

Please remove all indentations related and other extraneous changes and update this PR. Once done, I will be able to merge it. Feel free to reach out to us if you have any questions.

Thank you.

**Comment by Syknapse** [comment]
@David-Thapa Simply make sure you disable any style formatting on your IDE or text editor (VS Code or whatever you are using). Whether it's Prettier or ESLint or your editor's own style formatting.
The problems is if your editor has a different style formatting the the project when you hit save it might change the entire indentation of the file and instead of being able to see the specific changes you made to the file (the card you added) it shows up that you have changed the entire file.

Probably the easiest way to do it is to start again. Close this PR, create a new branch, disable all your formatting settings, add your card, and then submit a new PR.

If you are still having trouble let us know and we will surely find a way to help you.

**Comment by David-Thapa** [comment]
i will surely try creating a new PR.

**Pull request closed without merging**
