### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vibhor0**
Just added my contribution!

### CODE REVIEW

**Comment by Vibhor0** [comment]
Please add my card to your live site.

**Review by iatharva — CHANGES_REQUESTED** [review]
Just needed a little change in the comment on your card.
Your card's comment looks something like this  
`  <!-- ________ *TEMPLATE: MAKE A COPY* Contributor card START ________  -->`
`<!-- ________*END TEMPLATE* Contributor card END ________  -->`
You just need to replace `*TEMPLATE: MAKE A COPY*` and `*END TEMPLATE*`  with your name, both at the start and the end of your card.
Also, there is no need of adding a contributor name line in the comment.
After that, I will review the changes and merge your pull request.

**Review by Vibhor0 — COMMENTED** [review]
Implemented the changes.

**Comment by iatharva** [comment]
Thank you for your contribution and Good luck with the open-source ahead. 🙂

**Pull request merged**
