### PR TITLE
Adding Arvindh's card information

### PR DESCRIPTION
**Pull request by itsarvindh**
Added a new card, with my information. **And also aligned the near-next cards which were unaligned.**

### CODE REVIEW

**Comment by CandidDeer** [comment]
Closing this as your card is already live from a previous PR.

**Comment by itsarvindh** [comment]
I think there has been a confusion, as this is the first time am contributing to this repo! Can you please share the previous PR? And this is the only PR I have created! May there has been a name confusion! @CandidDeer

**Comment by CandidDeer** [comment]
@itsarvindh Oh no, so sorry - you indeed had a name twin! 😅 Thank you for pointing it out and for your contribution. I have merged it now. Happy Hacktoberfest!

**Comment by itsarvindh** [comment]
Lol, Ha ha ha! It's okay @CandidDeer, thank you for merging the PR! Happy Hacktoberfest

**Comment by itsarvindh** [comment]
It seems that this repo has been excluded from hacktoberfest. As i got this notification "YOUR PR/MR WAS SUBMITTED TO A REPOSITORY THAT HAS BEEN EXCLUDED FROM HACKTOBERFEST AS IT DOES NOT FOLLOW THE VALUES OF THE EVENT. IT WILL NOT COUNT TOWARDS YOUR PARTICIPATION."

@CandidDeer can you please check what's happening?

**Comment by CandidDeer** [comment]
Sadly, this seems to be true, yes. We've only just found out now. I'm sorry for the inconvenience!

**Comment by itsarvindh** [comment]
It's okay @CandidDeer. Happy to be a contributor!

**Pull request merged**
