### PR TITLE
Chris name card

### PR DESCRIPTION
**Pull request by Monstercn**
Adding Chris's name card to the index HTML

### CODE REVIEW

**Comment by Prajwalprakash3722** [comment]
Thank you for contribution, but just one last thing you have added your card at the end. Please add it at the top and I'll get this merged. 🚀🎉

**Review by Prajwalprakash3722 — COMMENTED** [review]
Pl add your card at the top.

**Comment by prathamesh-borse** [comment]
@Prajwalprakash3722 What do we have to do in this as it is not updated the pull request?

**Comment by Prajwalprakash3722** [comment]
> @Prajwalprakash3722 What do we have to do in this as it is not updated the pull request?

Let's wait !

**Review by AdityaSharma911 — APPROVED** [review]

**Pull request merged**
