### PR TITLE
add Thien Nguyen Card and fix the UI issue in index.html

### PR DESCRIPTION
**Pull request by ThienBNguyen**
add my card to index.html file and fix the UI issue.

### CODE REVIEW

**Review by Preet-Sojitra — CHANGES_REQUESTED** [review]
Your pull request is changing merge conflicts, so you are requested resolve the and then commit your changes. 
Here's how you can resolve the conflicts:
-  First of all pull the all the changes. Use `git pull origin`
- Then add your card 
- then commit the changes

After this we will review your code and merge it 👍

**Comment by CandidDeer** [comment]
Hi Thien, I have merged your card into the live version of our project. Regarding the UI changes, please be so kind and open a fresh pull request with these changes on top of the current (up-to-date) master branch and we'll be happy to merge and implement it. Please feel free to reach out to me if you have any questions. Thanks! ✨

**Comment by ThienBNguyen** [comment]
Hi CanDidDeer, I did not see the comment until now and thanks for fixing my conflicts. I have made a pull request and see my card name in the repo. what should i do next?

**Comment by CandidDeer** [comment]
Hi Thien, no worries. This PR has been merged and closed already. Your card is live. No further action is required from your side. 👍

**Pull request merged**
