### PR TITLE
Update Collins Boit card details

### PR DESCRIPTION
**Pull request by l00pinfinity**
I got a job, so I'm updating the card details and useful resources

### CODE REVIEW

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@l00pinfinity, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by l00pinfinity** [comment]
REPOSITORY HAS BEEN EXCLUDED FROM HACKTOBERFEST AS IT DOES NOT FOLLOW THE VALUES OF THE EVENT!!

**Comment by TenTraicion** [comment]
> REPOSITORY HAS BEEN EXCLUDED FROM HACKTOBERFEST AS IT DOES NOT FOLLOW THE VALUES OF THE EVENT!!

@l00pinfinity, Yeah, we are not perticipating in hactoberfest. We've removed the tags and topics regarding hactoberfest also.

**Comment by Syknapse** [comment]
@l00pinfinity congrats on the job. That's the best news we can hear here 🚀

**Pull request merged**
