### PR TITLE
JohnyP36's card

### PR DESCRIPTION
**Pull request by JohnyP36**
added a new card and modified the content with my info.

### CODE REVIEW

**Comment by TenTraicion** [comment]
Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by JohnyP36** [comment]
@TenTraicion , Thank you very much. I'm thinking of contributing to some translations of your repo files.

**Review by kamranzafar4343 — COMMENTED** [review]
looking fine to me

**Comment by kamranzafar4343** [comment]
> @TenTraicion , Thank you very much. I'm thinking of contributing to some translations of your repo files.

wonderful, keep on going

**Pull request merged**
