### PR TITLE
SHIKHA's card

### PR DESCRIPTION
**Pull request by creater-shikha**
Add my new card in index.html

### CODE REVIEW

**Review by Kushal997-das — COMMENTED** [review]
Great job @creater-shikha

**Comment by creater-shikha** [comment]
> Great job @creater-shikha

Thankyou so much

**Comment by Kushal997-das** [comment]
> > Great job @creater-shikha
> 
> Thankyou so much

Hello @creater-shikha If you want to contribute you can https://github.com/Kushal997-das/Project-Guidance

**Review by Syknapse — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
