### PR TITLE
JAGDF's Card

### PR DESCRIPTION
**Pull request by JAGDF**
I just input my card. Respond whether or not it's accepted. Thx 😀

### CODE REVIEW

**Comment by JAGDF** [comment]
Wait am I supposed to post a pull request?

**Comment by CandidDeer** [comment]
Thank you for your contribution. Your PR has been merged and your card will be live in a few moments.

**Comment by TenTraicion** [comment]
@CandidDeer, Kindly fix the URL issues here.

**Comment by CandidDeer** [comment]
@TenTraicion Ah, yes, sorry, didn't spot that - fixed it now. Thx for the heads-up!

**Pull request merged**
