### PR TITLE
Add the Traditional Chinese translation to the German maintainer guide

### PR DESCRIPTION
**Pull request by krushnarout**
# ✨ Pull Request

## ℹ️ About the PR

In this pull request, Added `maintainer_guide.zho-tc.md` to the German maintainer guide.

Thank you for considering this contribution!

### CODE REVIEW

**Comment by win21H2** [comment]
@TenTraicion Could you check if there's said maintainer_guide anywhere? Thanks!

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@krushnarout, Thanks for your contribution but,
1. We don't need to update translation table, or add such tables in translated docs except the main doc (English) of our project.
2. The table contents should be sorted alphabetically. 

so either it can be decarded or put on alphabetical order. Thanks.,

**Comment by krushnarout** [comment]
> Collaborator

Hi, I've arranged it in alphabetical order. Please check it. Thank you.

**Comment by krushnarout** [comment]
> @krushnarout, Thanks for your contribution but,
> 
> 1. We don't need to update translation table, or add such tables in translated docs except the main doc (English) of our project.
> 2. The table contents should be sorted alphabetically.
> 
> so either it can be decarded or put on alphabetical order. Thanks.,

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
:Merged: Congrats

**Pull request merged**
