### PR TITLE
Prettified Code

### PR DESCRIPTION
**Pull request by AbhishekThakur007**

### CODE REVIEW

**Comment by AbhishekThakur007** [comment]
Some changes.

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please add the hrefs to your resources. Thx.

**Comment by AbhishekThakur007** [comment]
> Please add the hrefs to your resources. Thx.

Thanks, @CandidDeer, for the correction.

**Comment by CandidDeer** [comment]
@AbhishekThakur007 You can either edit your contribution and repush, or it may be easier to close this PR and start with a fresh one. :)

**Comment by AbhishekThakur007** [comment]
> @AbhishekThakur007 You can either edit your contribution and repush, or it may be easier to close this PR and start with a fresh one. :)

I have done changes; please check

**Pull request closed without merging**
