### PR TITLE
Add bhavuk2002 card info

### PR DESCRIPTION
**Pull request by bhavuk2002**
added my card info in index.html

*my first pull request : )*

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Thank you for your first contribution ever. May I ask you to change your second resource to a real website tho? Don´t get me wrong, your input is totally valuable, but this project is supposed to provide link lists only plus it doesn't support embedded lists (<li> inside a <ul> inside a <li>), so I´d appreciate it if you could fix that and then I´ll merge. Thx!

**Comment by CandidDeer** [comment]
Thank you for your contribution. I have merged your PR and your card will be live in a moment.

**Comment by bhavuk2002** [comment]
Thank you so much for my first pitstop : )

**Comment by bhavuk2002** [comment]
One more thing, i think you guys should add Sponsor button.

**Pull request merged**
