### PR TITLE
b-luis' card

### PR DESCRIPTION
**Pull request by b-luis**
added my card to index.html file.

### CODE REVIEW

**Comment by CandidDeer** [comment]
Please remove files .travis.yml and workspace.xml from your PR so I can merge it. Thx,

**Comment by b-luis** [comment]
updated b-luis' card

**Comment by CandidDeer** [comment]
@b-luis the files are still there. I suggest you close this PR and start from scratch with a new one, following our project step by step instructions. Please reach out if you need help. Thx.

**Comment by b-luis** [comment]
Alright, thank you :)

**Pull request closed without merging**
