### PR TITLE
Tim's Card

### PR DESCRIPTION
**Pull request by timDeHof**
Added a new card and modify the content with my information to index.html file

### CODE REVIEW

**Comment by TenTraicion** [comment]
Looks like you have added to card at the end of the file. Please add it on the top. Once you are done open a pull request. We will be happy to merge your first contribution. Have a nice day :)

**Review by TenTraicion — CHANGES_REQUESTED** [review]
Looks like you have added to card at the end of the file. Please add it on the top. Once you are done open a pull request. We will be happy to merge your first contribution. Have a nice day :)

**Comment by timDeHof** [comment]
I have made the changes you requested. But I'm a little confused about what you want me to do. Should I create a new pull request or click the resolve conflicts button?

**Comment by TenTraicion** [comment]
Hi there, thank you for sharing your resources. They are live now!

**Comment by timDeHof** [comment]
Awesome!!!

**Pull request merged**
