### PR TITLE
Hardik 26 card

### PR DESCRIPTION
**Pull request by hardik-pratap-singh**
Added my card as mentioned.
Kindly merge my pr.

### CODE REVIEW

**Review by nzaih1999 — CHANGES_REQUESTED** [review]
@hardik-pratap-singh I've noticed that you've added 2 cards please delete one of the cards and then push your changes

**Comment by hardik-pratap-singh** [comment]
> Dear @nzaih1999, I have again made a pr where I have added a single card.
Kindly review it.

Thanks a lot!

**Comment by TenTraicion** [comment]
Merged via #1732.
, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

I am closing this PR as it's been merged via #1732.

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by hardik-pratap-singh** [comment]
Why your repo is showing excluded from hacktoberfest?

Is it not the part of it?

**Pull request closed without merging**
