### PR TITLE
add .idea folder of IntelliJ's IDS in gitignore

### PR DESCRIPTION
**Pull request by rohit-sagar256**

### CODE REVIEW

**Comment by CandidDeer** [comment]
@rohit-sagar256 What exactly does this PR accomplish? @Syknapse Please can you check this as well? Thx!

**Comment by rohit-sagar256** [comment]
> @rohit-sagar256 What exactly does this PR accomplish? @Syknapse Please can you check this as well? Thx!

it will ignore the .idea Folder created by Intellij IDEs when pushing to repo.

**Comment by CandidDeer** [comment]
> > @rohit-sagar256 What exactly does this PR accomplish? @Syknapse Please can you check this as well? Thx!
> 
> it will ignore the .idea Folder created by Intellij IDEs when pushing to repo.

Yes, I understand the code 😅 But why would that enhance the experience/be necessary?

**Comment by alsonick** [comment]
When working with IntelliJ IDEs the `.idea` folder gets generated for each project containing project-specific settings, ideally, we wouldn't want this to be pushed to production since settings might vary.

[https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-)

**Review by Syknapse — APPROVED** [review]
This is a useful improvement. Thank you for the contribution

**Comment by Syknapse** [comment]
@CandidDeer This can be merged now. I think it is useful to remove the .idea folder form the git history as it doesn't serve us really

**Comment by CandidDeer** [comment]
@Syknapse Thank you 👍🏻 @rohit-sagar256 Thank you - your contribution has been merged now and will be live in a moment. ✨

**Pull request merged**
