### PR TITLE
commit

### PR DESCRIPTION
**Pull request by ArpanBardhan**
I have modified my card.

### CODE REVIEW

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@ArpanBardhan, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by ArpanBardhan** [comment]
Thank You....

**Comment by ArpanBardhan** [comment]
Can you please explain to me what does the prettier check does. Is it some form of error that I should look out for ?

**Comment by TenTraicion** [comment]
> Can you please explain to me what does the prettier check does. Is it some form of error that I should look out for ?

@ArpanBardhan, our project has prettier integration for checking the code and format. So you shouldn't worry. It just check for errors in our code and style/reformat it if needed.

**Pull request merged**
