### PR TITLE
Amitkumar's card

### PR DESCRIPTION
**Pull request by 1-amitkumar**
Added a new card with my info

### CODE REVIEW

**Review by lax0248917 — CHANGES_REQUESTED** [review]

**Review by lax0248917 — COMMENTED** [review]
This all looks great. One last thing before we merge your pull request. Did you want the website titles visible in your card? If so then you would want to place that title where you have the sites url in plain text. What text you have between the opening and closing A tags will be what is visible to the end user. Let me know how you'd like me to proceed. Thanks 🚀

**Comment by prathamesh-borse** [comment]
@lax0248917 This Pull request has some conflicts can I solve that conflicts?

**Comment by lax0248917** [comment]
> @lax0248917 This Pull request has some conflicts can I solve that conflicts?

@prathamesh-borse  We are waiting for confirmation from the contributor if they want to add visible titles to their dev resources. After that then you can use GitKracken to fix the merge conflicts and merge the PR.

**Comment by Preet-Sojitra** [comment]
@1-amitkumar Congratulations!!! Your pr is merged. Have a nice day ahead

**Pull request merged**
