### PR TITLE
BhawanaSankhla's card

### PR DESCRIPTION
**Pull request by BhawanaSankhla11**
Add my card information

### CODE REVIEW

**Comment by Chirag-18** [comment]
You are having merge conflict in your pull request.Resolve it first.I was also having the same conflict

**Comment by BhawanaSankhla11** [comment]
How to remove merge conflicts,please guide.

**Comment by BhawanaSankhla11** [comment]
How to resolve merge conficts,please guide.

**Comment by Chirag-18** [comment]
> How to resolve merge conficts,please guide.

Click on resolve conflict and remove all the line which contain ====,<<<<<,>>>>> .My code got resolve by this you can also try.I am also a newbie so try it and let me know if this works or not.

**Comment by BhawanaSankhla11** [comment]
I did the same.But after resolving conflict when i tried to click on the mark as resolved this button is disabled.It's not working.

**Comment by BhawanaSankhla11** [comment]
how will we know where should i changed the code??

**Comment by TenTraicion** [comment]
@BhawanaSankhla11 and @Chirag-18 never try to solve merge conflicts unless you are told to do so by a project maintainer.

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@BhawanaSankhla11, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by Chirag-18** [comment]
Can you please tell me in which line your card is present in index.html file?My card is present but i cannot find it in code.
goel.chirag20@gmail.com is my email if you are able to get it please tell.

**Pull request merged**
