### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by dmytrovoytko**
Hi! Thank you for this project!
I'd like to contribute by adding Ukrainian translation, please consider my PR.

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse Please review this PR for feasibility to merge. Thx.

**Comment by TenTraicion** [comment]
@dmytrovoytko, @CandidDeer i think the links need to be checked properly.

**Comment by dmytrovoytko** [comment]
> the links need to be checked properly
@TenTraicion Agree! I checked several times and be glad to correct if something is missed, any particular issues?

**Comment by TenTraicion** [comment]
@dmytrovoytko, it's a great addition to our project and thanks a bunch for that. There are some link issues, like in the translation table, the links are broken. you may check the reference on other translations of our project.

That's why i asked to check the links properly, cause there might be other issues in there as they are all dynamic. Thanks.

**Review by Syknapse — APPROVED** [review]
Great stuff, thank you for the contribution, it's very helpful to add a new translation 💪🏼🇺🇦
From my part once any issues have been resolved it's good to merge

**Comment by dmytrovoytko** [comment]
@TenTraicion > translation table
I really missed those relative links, thank you. 
Fixed! And I checked the rest of relative links, looks ok.

**Review by TenTraicion — APPROVED** [review]
looks good

**Comment by TenTraicion** [comment]
@dmytrovoytko, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by dmytrovoytko** [comment]
@CandidDeer @TenTraicion @Syknapse Thank you all! 💛💙

**Comment by Syknapse** [comment]
> @CandidDeer @TenTraicion @Syknapse Thank you all! 💛💙

All thanks to you for contributing to our project and making it more useful for more people.

**Pull request merged**
