### PR TITLE
Fix Repo stat 

### PR DESCRIPTION
**Pull request by PencilNavigator**
https://github.com/anuraghazra/github-readme-stats/issues/2415

Easy fix. Just change the github-readme-stats Default URL to another one.

(Before change the repository's README looks like this.)
图片

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse Please can you review and approve/reject this general enhancement? Thx!

**Comment by TenTraicion** [comment]
@PencilNavigator, the url is working perfectly from my end though:

image

**Comment by PencilNavigator** [comment]
@TenTraicion See https://github.com/anuraghazra/github-readme-stats/issues/2402.
The author said that the main demo service is Fixed 4 days ago, but there are still reports saying that the main demo service not working.
So it's best to use another URL instead of the original url.

**Review by TenTraicion — APPROVED** [review]
@PencilNavigator, okay a change of url doesn't hurt. but is it hosted by you or will it have any trouble again in the future? what will we do then? change to another one?

sorry for a bunch of questions but i am a little bit curious.

**Comment by PencilNavigator** [comment]
@TenTraicion I can't guarentee that the link will work for long time (since it's community provided). But using the default Demo link has more issue then using this.

The creator of github-readme-stats has his readme-stats down just a few minutes ago. I checked, and he is using the default README demo service.
Pic(Screenshot on 2023/1/18 13:38 UTC+8

**Comment by TenTraicion** [comment]
@PencilNavigator,  Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Pull request merged**
