### PR TITLE
Improved Hero-Section UI

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
Hero section layout is improved and it looks clean and good from the previous one. A font name Domine is added for h1 tag !! Some effect on hover is also added to contibution btn.

### CODE REVIEW

**Comment by nzaih1999** [comment]
Hey  thanks for your contribution, Would you please provide a screenshot of how it looks on your local machine?

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@ZubairImtiaz3, Thanks for your contribution. Kindly provide some ss of your changes.

**Comment by ZubairImtiaz3** [comment]
### The herosection looks like this on live site.
before
### The herosection looks like this after my changes.
after
### The herosection btn has not any hover effect like this on live site.
buttonbefore
### Give it a slight hover effect like this.
buttonafter

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@ZubairImtiaz3, Thanks a lot for the enhancement. It's beautiful. Just one final review from @Syknapse and we are good to go.

for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

**Review by Syknapse — APPROVED** [review]
Looks good to me. Thank you for the contribution. We can go ahead and merge this.

**Comment by TenTraicion** [comment]
@ZubairImtiaz3, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Pull request merged**
