### PR TITLE
Chethana's card

### PR DESCRIPTION
**Pull request by Chethanasv-22**
Added Chethana's card information

### CODE REVIEW

**Comment by Prajwalprakash3722** [comment]
Hey @Chethanasv-22, I would love to merge your contribution but one small issue is there, you have added the card at the bottom, please add it one line below the template. 👌

**Review by Prajwalprakash3722 — CHANGES_REQUESTED** [review]
Add this in the top just one line below the template.

**Comment by Chethanasv-22** [comment]
Sure. I'll do the changes. And thank you for considering my pull request.

**Comment by iatharva** [comment]
As you have submitted a new pull request #953 , I am closing this pull request.

**Pull request closed without merging**
