### PR TITLE
2ndUpdate index.html

### PR DESCRIPTION
**Pull request by MrChinmay03**
name added

### CODE REVIEW

**Review by Preet-Sojitra — APPROVED** [review]

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@MrChinmay03, , Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

**Comment by MrChinmay03** [comment]
> @MrChinmay03, , Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

Bhaiya can u pls tell me what was wrong in my pull req

**Comment by TenTraicion** [comment]
> > @MrChinmay03, , Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!
> 
> Bhaiya can u pls tell me what was wrong in my pull req

@MrChinmay03, there is nothing wrong with your pull request. That's why it has been merged. The other PR's #1592 and #1594 are considered duplicate PR so there have been closed!

**Comment by MrChinmay03** [comment]
> > > @MrChinmay03, , Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!
> > 
> > 
> > Bhaiya can u pls tell me what was wrong in my pull req
> 
> @MrChinmay03, there is nothing wrong with your pull request. That's why it has been merged. The other PR's #1592 and #1594 are considered duplicate PR so they have been closed!

Ok bhaiya

**Pull request merged**
