### PR TITLE
Added new card named Hina.

### PR DESCRIPTION
**Pull request by hmmalic**
Added, 3 dev resources under the card name HINA M. Also added personal twitter handle and username.

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Hello, to follow our guidelines, please insert your card directly after line 117 (after this line:  `========= Paste YOUR CARD directly BELOW this line =========`.)
This will ensure our file stays tidy. Once you have made this requested change, I'll be happy to merge your contribution. Thanks.

**Comment by hmmalic** [comment]
> Hello, to follow our guidelines, please insert your card directly after line 117 (after this line: `========= Paste YOUR CARD directly BELOW this line =========`.) This will ensure our file stays tidy. Once you have made this requested change, I'll be happy to merge your contribution. Thanks.


May be you mean to say line number 107 ?

**Comment by CandidDeer** [comment]
No, I do mean line no. 117.

**Comment by hmmalic** [comment]
see this screenshot please as I am little confused since line 107 is after <======>
where as 117 is in the middle ,

[cid:64f5ba8a-3be2-4f5c-bf4d-0f2de9f493c2]
________________________________

**Comment by CandidDeer** [comment]
The screenshot doesn't show, I'm sorry. At any rate. You need to insert your card after the line that says "========= Paste YOUR CARD directly BELOW this line =========". Thanks.

**Comment by hmmalic** [comment]
> The screenshot doesn't show, I'm sorry. At any rate. You need to insert your card after the line that says "========= Paste YOUR CARD directly BELOW this line =========". Thanks.

I have made the changes , can u please check . Thanks

**Pull request merged**
