### PR TITLE
Added my card information

### PR DESCRIPTION
**Pull request by arghanath007**
Added a card with my own information on it.

### CODE REVIEW

**Review by iatharva — CHANGES_REQUESTED** [review]
Looks like you have added your card immediately below the template, you have to add your card just below the template but after the comments as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

**Comment by arghanath007** [comment]
I have a made a commit with the fixes. See if it works now.

**Review by iatharva — APPROVED** [review]

**Comment by arghanath007** [comment]
All good now?

**Review by dilshankarunarathne — APPROVED** [review]
Hello @arghanath007, it looks good now. 
Sorry for the delay. Your pull request will be merged ASAP.

**Comment by dilshankarunarathne** [comment]
Congratulations 🎉❤
Your pull request was merged. 
You will be able to see your card on the [project website](https://syknapse.github.io/Contribute-To-This-Project/).

**Comment by arghanath007** [comment]
It's ok. Thank you

**Pull request merged**
