### PR TITLE
Anurag's card

### PR DESCRIPTION
**Pull request by Danuragtiwari**
Added my card

### CODE REVIEW

**Review by Preet-Sojitra — COMMENTED** [review]
Hey Anurag, you have left the resources section of your card blank. You haven't added any resources, it would be great if you can add some useful resources. Commit your changes after adding those resources.

**Comment by Danuragtiwari** [comment]
yes ,Now its all filled!!

**Review by nzaih1999 — CHANGES_REQUESTED** [review]
Hello I've noticed you've added a lot of  code can you just add your card alone?

**Comment by Danuragtiwari** [comment]
once check my 4 commits ! is it fine?

**Comment by Preet-Sojitra** [comment]
@Danuragtiwari Congratulations, your card has been merged. You can now view your card on the project's website.
Hope you have learnt new things by contributing to this project.
Have a nice day :)

**Comment by Danuragtiwari** [comment]
Thankyou sir!!

**Pull request merged**
