### PR TITLE
Greek Language Support

### PR DESCRIPTION
**Pull request by Periklis03**
Added Greek Language Support to translation and Read.me

### CODE REVIEW

**Comment by ascodeasice** [comment]
Hi, the link of step 2,3,4 in quick access table is invalid, and please delete the pdf in the next commit, thanks

**Comment by Periklis03** [comment]
Thanks for the response it should be fixed now!

Στις Δευ 25 Δεκ 2023 στις 7:16 μ.μ., ο/η Leo Wang ***@***.***>
έγραψε:

**Comment by darkdevil3610** [comment]
test

**Comment by ascodeasice** [comment]
Thanks for your contribution!

**Pull request merged**
