### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by archielicious**
I have added my updated card, please find my card named Archishman Dash from previous commit and change it with the new one

### CODE REVIEW

**Comment by ascodeasice** [comment]
Hi, I've updated your card, you can check it by going to the website preview.

**Comment by ascodeasice** [comment]
If everything is fine, tell me and I'll close this PR

**Comment by archielicious** [comment]
Yes, I have checked the live website. Everything is fine.

**Comment by archielicious** [comment]
I have added some more contact information to my card, please update it
according to the newest commit 3a68b84.

Thank you

Archishman Dash

**Comment by ascodeasice** [comment]
Hi, I've updated it.
If you want to update your card in the future, you can check archive_15.json, and update your info in it. Then we will check your PR.

**Pull request closed without merging**
