### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dannymonareng**
copied and pasted contributor's card

### CODE REVIEW

**Review by nzaih1999 — CHANGES_REQUESTED** [review]
hello @dannymonareng  I've noticed that you've made changes to an existing card. copy the template card above that and add your details in it. In case you're having issues feel free to tell me Ill be happy to help

**Review by AliReza1083 — COMMENTED** [review]
I reviewed your codes, It was ok.
Wish you all the best.

**Comment by dannymonareng** [comment]
Thank you for the feedback
Regards

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@dannymonareng, Thanks for your contribution. I have fixed your card and merged it with our main project. You can find your card in our website or by clicking: [here](https://syknapse.github.io/Contribute-To-This-Project/)!

**Pull request merged**
