### PR TITLE
Zijian1799's card

### PR DESCRIPTION
**Pull request by zijian1799**
added a new card and modified it with my info into index.html

### CODE REVIEW

**Review by win21H2 — CHANGES_REQUESTED** [review]
Hello @zijian1799, Please move your card to the top of the HTML file just under the template section. Thanks! I will merge it after you make the changes :)

**Comment by win21H2** [comment]
For reference, place it here :)

image

**Review by win21H2 — APPROVED** [review]
Thanks! I will merge it and you should be able to see your card at the top of the website in around 2 mins. Congrats!

**Comment by zijian1799** [comment]
Thanks a lot. Have a good day.

**Pull request merged**
