### PR TITLE
Add oj card

### PR DESCRIPTION
**Pull request by ojninja16**

### CODE REVIEW

**Review by Preet-Sojitra — APPROVED** [review]

**Comment by Preet-Sojitra** [comment]
Congratulations @ojninja16  your pull request has been merged. You can view your card on [project's website](https://syknapse.github.io/Contribute-To-This-Project/). Hope you have learnt new things. 
All the best for your future journey in open source.
Have a nice day :)

**Comment by ojninja16** [comment]
Hi @Preet-Sojitra !! I am new to open source could you suggest some good projects to contribute to...thanks!

**Comment by Preet-Sojitra** [comment]
You can visit this [website](https://goodfirstissue.dev/). This website contains list of repos having good first issues, means beginner can contribute. Select the language (say python, JS or whatever) and it will give list of repos.
You can visit this [website](https://finder.eddiehub.io/) also. 
You can also check the `explore` section (available on top on github home page) in github, there you will get trending repos and other repos as well, look for the issues in that repos and then start contributing to them.

**Comment by dannymonareng** [comment]
thank you

**Pull request merged**
