### PR TITLE
kishanrajput23's Card

### PR DESCRIPTION
**Pull request by kishanrajput23**

### CODE REVIEW

**Review by CandidDeer — APPROVED** [review]

**Comment by kishanrajput23** [comment]
I have resolved the conflict.

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Your PR is replacing the content of another contributor's card. This is not how our project works. Please feel free to start over, following our project guidelines step by step. Thx.

**Comment by CandidDeer** [comment]
@kishanrajput23 Please note that we will be closing any PRs with unresolved change requests 7 days after initial opening. Thx.

**Comment by kishanrajput23** [comment]
okay I'm closing this PR and I'll start again as I can see there are a lot of conflicts in my PR.

**Pull request closed without merging**
