### PR TITLE
Prantik Mukherjee's Card

### PR DESCRIPTION
**Pull request by champmaniac**
Add my card information to index.html file

### CODE REVIEW

**Review by shreyshreyansh — COMMENTED** [review]
Edit this file again because there are lot of changes(indentation) done in this PR

**Comment by champmaniac** [comment]
> Edit this file again because there are lot of changes(indentation) done in this PR

Okay yes i did the indentation by mistake!
i'm making it perfect!

**Review by prathamesh-borse — CHANGES_REQUESTED** [review]
These Below Changes you have to done and send your PR again.

- Give Space in 108 above and 
- Give Space in 138 below

**Comment by champmaniac** [comment]
> These Below Changes you have to done and send your PR again.
> 
> * Give Space in 108 above and
> * Give Space in 138 below

Okay i'm doing it right away

**Comment by champmaniac** [comment]
I'm creating a new PR , have made alot indentations

**Comment by champmaniac** [comment]
Made a PR again, please do check it

**Review by prathamesh-borse — APPROVED** [review]
These look fine Now your PR will be merged after @shreyshreyansh will review your indentation.

**Comment by champmaniac** [comment]
You approved wrong PR it seems i have created another PR with all the indentations solved #904

**Comment by prathamesh-borse** [comment]
Okay, Don't Worry I Will approved your Another PR Once My Laptop Get
Charged 👍

**Comment by lax0248917** [comment]
Card was added in PR #904. Closing this PR as it is a duplicate.

**Comment by champmaniac** [comment]
Yes definitely!

**Pull request closed without merging**
