### PR TITLE
Rishika's card added

### PR DESCRIPTION
**Pull request by risacker**
Rishika's card added to index.html file.

### CODE REVIEW

**Review by dipeshbabu — CHANGES_REQUESTED** [review]
@risacker Hey, make sure your code is below line 117
code

**Review by risacker — COMMENTED** [review]
Changes made

**Review by dipeshbabu — APPROVED** [review]
LGTM

**Comment by lax0248917** [comment]
Hello @risacker, thank you for contributing! 🎉 Your PR looks great, we will get this merged right away. Best of luck with your cyber-security studies and app development. 🚀

**Comment by risacker** [comment]
> LGTM

Thank you:)

**Comment by risacker** [comment]
> Hello @risacker, thank you for contributing! 🎉 Your PR looks great, we will get this merged right away. Best of luck with your cyber-security studies and app development. 🚀

Thank you:)

**Pull request merged**
