### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by MrChinmay03**
Pls check the edits now and please suggest me with other beginner friendly issues

### CODE REVIEW

**Comment by TenTraicion** [comment]
Dear @MrChinmay03, Your card has already been added to the project via #1593 and you don't need to add it anymore. You can check your card live in: [this link](https://syknapse.github.io/Contribute-To-This-Project/). Thanks for your contribution.

**Comment by MrChinmay03** [comment]
> Dear @MrChinmay03, Your card has already been added to the project via #1593 and you don't need to add it anymore. You can check your card live in: [this link](https://syknapse.github.io/Contribute-To-This-Project/). Thanks for your contribution.

Was there some error in my code?

**Comment by MrChinmay03** [comment]
Actually my name's starting letter are not in capital letter(in the website) but I inserted it in capital in my code

**Comment by TenTraicion** [comment]
@MrChinmay03 It will be fixed soon. let me know if there is any other changes you want in your card!

**Comment by MrChinmay03** [comment]
> @MrChinmay03 It will be fixed soon. let me know if there is any other changes you want in your card!

Bhaiya I was asking did I made any mistakes in the code or in the GitHub processes

**Comment by TenTraicion** [comment]
@MrChinmay03, No. Your card has been merged successfully and added to the project perfectly. you can find your name card by clicking this link: https://syknapse.github.io/Contribute-To-This-Project/

**Comment by MrChinmay03** [comment]
> @MrChinmay03, No. Your card has been merged successfully and added to the project perfectly. you can find your name card by clicking this link: https://syknapse.github.io/Contribute-To-This-Project/

Thank Bhaiya can u please suggest or assign some issues so that I can get started with open source 
I have currently learned HTML,CSS,C++

**Comment by TenTraicion** [comment]
> > @MrChinmay03, No. Your card has been merged successfully and added to the project perfectly. you can find your name card by clicking this link: https://syknapse.github.io/Contribute-To-This-Project/
> 
> Thank Bhaiya can u please suggest or assign some issues so that I can get started with open source I have currently learned HTML,CSS,C++

you can search in GitHub with the keyword: `good-first-issue` and contribute there. There are lot of issues for beginners only!

**Comment by MrChinmay03** [comment]
> > > @MrChinmay03, No. Your card has been merged successfully and added to the project perfectly. you can find your name card by clicking this link: https://syknapse.github.io/Contribute-To-This-Project/
> > 
> > 
> > Thank Bhaiya can u please suggest or assign some issues so that I can get started with open source I have currently learned HTML,CSS,C++
> 
> you can search in GitHub with the keyword: `good-first-issue` and contribute there. There are lot of issues for beginners only!

Oki 
Thanks for your assistance

**Pull request closed without merging**
