### PR TITLE
added hardik card

### PR DESCRIPTION
**Pull request by hardik-pratap-singh**
I have now added a card. 
Kindly merge my pr.

thanks a lot !

### CODE REVIEW

**Review by nzaih1999 — APPROVED** [review]
Hello hacker @hardik-pratap-singh . Thanks for your contribution. Your card will be live in a few. Happy hacking!

**Comment by hardik-pratap-singh** [comment]
> Hello hacker @hardik-pratap-singh . Thanks for your contribution. Your card will be live in a few. Happy hacking!

Dear @Syknapse,

Till now your repo was live on my hacktoberfest page.
Timer was going on from last 4 days

Just now it is showing excluded from hacktoberfest.
Kindly look into this matter please ! 

Thanks a lot !

**Comment by Syknapse** [comment]
> 

Can you please explain to me a bit more what you mean. Where have you seen it excluded, can you pass a link?

**Comment by hardik-pratap-singh** [comment]
> Can you please explain to me a bit more what you mean. Where have you seen it excluded, can you pass a link?

I am attaching the official images of hacktoberfest page of my profile. 


IMG_20221007_115633


IMG_20221007_115618

**Comment by Syknapse** [comment]
Ok thanks, yeah we have realised that we've been excluded from the event. That's unfortunate but also falls within the rules of the event as this is mainly a tutorial project

**Comment by hardik-pratap-singh** [comment]
> Ok thanks, yeah we have realised that we've been excluded from the event. That's unfortunate but also falls within the rules of the event as this is mainly a tutorial project

No issues.
Thanks !

**Pull request merged**
