### PR TITLE
Yurvaj-singh-card

### PR DESCRIPTION
**Pull request by YuvrajSHAD**
i learned Html But It was Knowing the way We Can implement It. And All thanks To You!
Love You Dude!
Thank You.

### CODE REVIEW

**Comment by YuvrajSHAD** [comment]
Please Accept my Pull request so that in future i can access It.!

**Review by AdityaSharma911 — CHANGES_REQUESTED** [review]
Insert your card inside the HTML body

**Comment by YuvrajSHAD** [comment]
Sir,I don't understand how do I do this.???



On Oct 1, 2020 at 09:26, Aditya Sharma <notifications@github.com> wrote:

*@AdityaSharma911* requested changes on this pull request.

Insert your card inside the HTML body

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Syknapse/Contribute-To-This-Project/pull/590#pullrequestreview-499992449>,
or unsubscribe

**Comment by Syknapse** [comment]
@YuvrajSHAD good job on moving the card into the body of the HTML as requested. 
In the original spec you were supposed to paste your card at the beginning of the file not the end, but it doesn't make a difference once it is done correctly. So I did merge your PR. thank you for your contribution

**Comment by YuvrajSHAD** [comment]
Thank you! I appreciate it sir



On Oct 4, 2020 at 17:05, Syk Houdeib <notifications@github.com> wrote:

@YuvrajSHAD <https://github.com/YuvrajSHAD> good job on moving the card
into the body of the HTML as requested.
In the original spec you were supposed to paste your card at the beginning
of the file not the end, but it doesn't make a difference once it is done
correctly. So I did merge your PR. thank you for your contribution

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Syknapse/Contribute-To-This-Project/pull/590#issuecomment-703242310>,
or unsubscribe

**Pull request merged**
