### PR TITLE
Add Salil's card

### PR DESCRIPTION
**Pull request by chincholikarsalil**
Added my card to the [index.html](https://github.com/Syknapse/Contribute-To-This-Project/blob/master/index.html) file

### CODE REVIEW

**Comment by chincholikarsalil** [comment]
@AdityaSharma911 
Can you please review this PR?

**Review by glaukiol1 — APPROVED** [review]
Thanks for contributing! I hope you have fun in the future in contributing to open source software. Approved

**Comment by chincholikarsalil** [comment]
@glaukiol1 Thanks a lot! 
Looking forward to seeing this PR get merged.

**Comment by glaukiol1** [comment]
Of course! Just please note that I cant merge PRs since I dont have write access, I only review. You need a staff member to merge this. Thanks!

**Comment by chincholikarsalil** [comment]
Yes, got it. Thanks for approving!

**Review by AdityaSharma911 — APPROVED** [review]

**Comment by AdityaSharma911** [comment]
@chincholikarsalil Thanks for contributing!

**Pull request merged**
