### PR TITLE
martiancactus's card

### PR DESCRIPTION
**Pull request by MartianCactus**

### CODE REVIEW

**Review by ibrahimdevop21 — CHANGES_REQUESTED** [review]
Hi @MartianCactus !
---
Thanks for your contributor card—it looks great! I have a few suggestions to make it even better. Could you provide more details in the "About" section and update the resource links to actual websites? This will help others connect with you and find the resources easily.

Looking forward to your updates!

Best,
@ibrahimdevop21

**Comment by MartianCactus** [comment]
hi, added the stuff you specidied! Do I need to opena notehr PR?

**Comment by MartianCactus** [comment]
trying the close with comment funcionality

**Review by ibrahimdevop21 — APPROVED** [review]
Hi @MartianCactus,
--
Thank you so much for your contribution! I can see that you've fixed the minor issues I mentioned before, and I feel confident merging your card now. Welcome to the open-source community!

Approved! ✅
--
Best,
@ibrahimdevop21

**Comment by ibrahimdevop21** [comment]
@MartianCactus 
--
Sorry for the dellay

**Pull request merged**
