### PR TITLE
Add Tanmay123Gorasha card info

### PR DESCRIPTION
**Pull request by Tanmay123Goraksha**
Thank You For Creating Such a Simple Tutorial for beginners like me. Please accept my pull request

### CODE REVIEW

**Review by ibrahimdevop21 — CHANGES_REQUESTED** [review]
Hi @Tanmay123Goraksha,

Thank you for your contribution! May this be your first step into the world of the open-source community. While you've successfully copied the template and placed it in the right location, I noticed a couple of things:

Please replace the placeholder text for your Twitter and GitHub handles in the anchor elements.
Substitute "resource 1," "resource 2," and "resource 3" with the actual resource names.
I'm looking forward to seeing your updated code and will be more than happy to merge your card once these adjustments are made.

**Review by Tanmay123Goraksha — COMMENTED** [review]
Added the requested changes

**Review by ibrahimdevop21 — CHANGES_REQUESTED** [review]
Looks great! We're almost there. The final thing to do: if you don't have a Twitter account, please remove the associated <a> and <i> tags:

<i class="fab fa-x-twitter"></i>
<a href="https://www.twitter.com/your_user_handle" target="_blank">None</a>

Once that's done, we'll be ready to merge your card. Thanks!

**Comment by Tanmay123Goraksha** [comment]
> Looks great! We're almost there. The final thing to do: if you don't have a Twitter account, please remove the associated and tags:
> 
> [None](https://www.twitter.com/your_user_handle)
> 
> Once that's done, we'll be ready to merge your card. Thanks!

removed the tag

**Review by ibrahimdevop21 — APPROVED** [review]
Hi @Tanmay123Goraksha,

Thank you again for all the hard work you've put in. Everything looks great! I'll merge your card now, and you'll be able to see it live on our website in a few minutes.

**Pull request merged**
