### PR TITLE
Rohit's Card

### PR DESCRIPTION
**Pull request by aarkaynegi**
Thanks for the opportunity.

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please note that you are not allowed to make changes directly to the template content. Instead, copy the template content and paste it, starting in line 117. Then fill it in with your own content. Please feel free to reach out with any questions. Once this change request has been resolved, I'll be happy to merge your PR. Thx.

**Review by aarkaynegi — COMMENTED** [review]
Changes: Updated index.html

**Comment by aarkaynegi** [comment]
@CandidDeer. Changes made as advised and resolved conflict. Kindly merge PR. Thanks for your support.

**Review by CandidDeer — APPROVED** [review]

**Comment by CandidDeer** [comment]
Thank you for your contribution and for making the requested changes! I have now merged your PR and your card will be live in a moment.

**Comment by aarkaynegi** [comment]
Thank you so much @CandidDeer.

**Pull request merged**
