### PR TITLE
Updated the index.html file

### PR DESCRIPTION
**Pull request by saxam0**
Signed-off-by: Saksham <sakshamcci@gmail.com>

### CODE REVIEW

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@saxam0, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

**Comment by saxam0** [comment]
> @saxam0, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!

Why the PR is closed?

**Comment by TenTraicion** [comment]
> > @saxam0, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!
> 
> Why this PR is closed now?

@saxam0 , Your card has been added to our website which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)! That's why This PR has been closed!

**Comment by saxam0** [comment]
> > > @saxam0, Thanks for your Contribution. and Congrats on your first PR Merge in this project. Your Card will be live within ~2-3 minutes, which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)!
> > 
> > Why this PR is closed now?
> 
> @saxam0 , Your card has been added to our website which can be found: [Here](https://syknapse.github.io/Contribute-To-This-Project/)! That's why This PR has been closed!

How can I contribute more?

**Comment by TenTraicion** [comment]
@saxam0, By translating, being a maintainer, or searching for other `good-first-issue` in github and contributing there.

**Pull request merged**
