### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by r4huldeveloper**
Add my card information

### CODE REVIEW

**Review by TenTraicion — APPROVED** [review]

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please add your handle to the linkedin href and ass a third useful resource. Thx.

**Comment by r4huldeveloper** [comment]
I already mentioned my Linkedin so what's the problem ?

**Review by r4huldeveloper — COMMENTED** [review]
I updated "href" for linkedin and also add the third learning resource.

**Comment by CandidDeer** [comment]
Thank you for your contribution. I have merged your PR and your card will be live in a moment.

**Comment by r4huldeveloper** [comment]
Thanks @CandidDeer ! Take care , be happy and healthy

**Pull request merged**
