### PR TITLE
Prettier Styling

### PR DESCRIPTION
**Pull request by dquindara8**
Hello, sorry for the delay in time. I hope that I did the right thing here. I styled the document with Prettier as requested.

### CODE REVIEW

**Comment by dquindara8** [comment]
Hello how do I correct the mark above which states "All checks have failed"?

**Comment by dquindara8** [comment]
The name "Contribute-nameCard-branch1" is apart of this same project, Syknapse. It is no different. It was created during the making of the card for the site.

**Comment by Preet-Sojitra** [comment]
It seems that you haven't added your card because commit shows that only 1 line of code is changed?

**Comment by TenTraicion** [comment]
@dquindara8 , you card already is in our project. It was merged: #1624 , so I am closing this PR as it has no value!

**Comment by dquindara8** [comment]
Ok, thank you.

**Pull request closed without merging**
