### PR TITLE
Maintainer' guide translation in italian

### PR DESCRIPTION
**Pull request by danieled-it**
Hey  @Syknapse / All maintainers,
I'm also a wanna-be contributor in Open Source and stumbled in this project, really like the concept behind it!
I'm familiar enough with the concept of PRs and so on, working in IT, but I'm still looking to give some sort of impact also out of office hours 😄 .

The translation kept still some English terms, reality is that in an IT context in Italian a bunch of words simply do not exist or they do not even make sense when translated, I tried anyway to keep in brackets their translation when it made sense.

Cheers!
Daniele

### CODE REVIEW

**Review by nzaih1999 — APPROVED** [review]
Whoa @danieled-it  this is amazing!

**Comment by nzaih1999** [comment]
Thank you so much for this 🙏

**Comment by Syknapse** [comment]
Thank you for this @danieled-it great work, we appreciate it. 
The next step if you ask me is for you to join the maintainers' team where you can have even more impact on the project. And we always love to have enthusiastic people like you with us. If this is something you are interested in, checkout the [Maintainer's guide](https://github.com/Syknapse/Contribute-To-This-Project/blob/master/maintainer_guide.md) adn let me know if you'd like to join us.

**Comment by Syknapse** [comment]
Hahaha oh I'm totally sorry, I entered into automatic mode and I always tell people to read the guide before joining and I didn't even think about it 😂😂 apologies. 

Sure, you can dedicate the time you want to it. Right now we have a great bunch of active maintainers and it's easy to lend a hand when you want.

**Comment by Syknapse** [comment]
I've added you to the project as a maintainer.
Please join us on our Discord server where you can meet the rest of the maintainers and get any help you need as you familiarise yourself with the project
https://discord.gg/Ndd2vWRX

**Pull request merged**
