### PR TITLE
Asset added, with resources

### PR DESCRIPTION
**Pull request by s-Hale**

### CODE REVIEW

**Review by iatharva — CHANGES_REQUESTED** [review]
- I am curious why you removed and added the space again. 
- Also looks like you have added your card at the end of the file while it needed to be at the top below the template, you can refer to step 5 given [here](https://github.com/Syknapse/Contribute-To-This-Project)

Once the changes are done, I will review and merge your PR.

**Comment by s-Hale** [comment]
> * I am curious why you removed and added the space again.
> * Also looks like you have added your card at the end of the file while it needed to be at the top below the template, you can refer to step 5 given [here](https://github.com/Syknapse/Contribute-To-This-Project)
> 
> Once the changes are done, I will review and merge your PR.

I have a feeling my eslint settings did that - changing tab space, something along those lines. It wasn't intentional.

**Comment by iatharva** [comment]
Okay, looks good then, Thank you for your contribution and hope you have a great journey ahead in open source :)

**Comment by s-Hale** [comment]
> Okay, looks good then, Thank you for your contribution and hope you have a great journey ahead in open source :)

Thanks, sorry for the space trouble.
Could this have the 'hacktoberfest accepted' label added? Thanks :)

**Pull request merged**
