### PR TITLE
Update arabic.md

### PR DESCRIPTION
**Pull request by abhinab-choudhury**

### CODE REVIEW

**Comment by abhinab-choudhury** [comment]
Update Arabic version of README to contribute to the issue: #2826  #3029

**Comment by CandidDeer** [comment]
@Syknapse Please check for feasibility to merge. Thx.

**Comment by TenTraicion** [comment]
#2826

**Comment by TenTraicion** [comment]
@abhinab-choudhury you dont need to remove any conflicts, let the maintainer handle that. and if possible remove index.html from your pr

**Pull request closed without merging**
