### PR TITLE
Lucas Hogg's card

### PR DESCRIPTION
**Pull request by lucashogg**
Added my card to index.html file

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Your PR is trying to change all lines of code inn our PR. This shouldn't happen. There is no need for you to change any code outside your own card. Please fix. thx.

**Comment by lucashogg** [comment]
Hi, thank you for letting me know. I'm new to contributing, and after looking through the GitHub docs on how to resolve merge conflicts, I'm still unsure of what I need to remove/replace when I click through to the code editor page. Would you mind giving me some direction?

**Comment by lucashogg** [comment]
I may have figured it out...

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@lucashogg, Congratulations on your PR Merge, and Thanks for your Contribution. You can check your card on our [Live Website](https://syknapse.github.io/Contribute-To-This-Project)! It may take 2-3 minutes to make your card visible on our website. 

Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Pull request merged**
