### PR TITLE
on hover backtotop button animates

### PR DESCRIPTION
**Pull request by harshita-2003**
On hovering the back to top button linearly animates top-down

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse please review this general enhancement. Thx.

**Comment by harshita-2003** [comment]
@CandidDeer @Syknapse kindly acknowledge and merge the pr

**Comment by TenTraicion** [comment]
@harshita-2003, kindly elaborate the changes and provide screenshots/gif/videoclips. Thanks

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@harshita-2003, kindly elaborate the changes and provide screenshots/gif/videoclips. Thanks

**Comment by harshita-2003** [comment]
@TenTraicion here's the videoclip

https://github.com/Syknapse/Contribute-To-This-Project/assets/119532943/e75c5b7f-b96b-4a26-883c-874e52e91442

**Review by TenTraicion — APPROVED** [review]
Approve: first time contribution

**Pull request merged**
