### PR TITLE
Kamranzafar4343's card

### PR DESCRIPTION
**Pull request by kamranzafar4343**

### CODE REVIEW

**Review by kamranzafar4343 — COMMENTED** [review]
reviewed my card

**Review by kamranzafar4343 — COMMENTED** [review]
Anyone can tell me why conflicts are not solved?

**Comment by kamranzafar4343** [comment]
@CandidDeer can you please have a look at this?

**Review by CandidDeer — APPROVED** [review]

**Comment by CandidDeer** [comment]
Thank you for your contribution. I have merged your PR and your card will be live in a moment. Conflicts often only happen due to no fault of the contributer, when f.e. the contributer works on one version of the index.html, adding his card and another contributor makes a PR in the meantime. No worries. Your actual content was perfect. 🥇 BR

**Pull request merged**
