### PR TITLE
Real Contribution | Fixed Layout, Update Libraries, Formatted Code, Added Card

### PR DESCRIPTION
**Pull request by chankruze**
@Syknapse Consider this pull request as a real contribution. I was just passing by and show the mess here, being a developer it always bugs me when i see things which we are easily able to fix are left like they have no value. I could have just added my card and leave like others, but i am not like rest of them, it hurts if i avoid things which i can do, so below are those changes.

**Changelog**

1. Add Chandan's Card
2. Remove text-decoration from anchor tag
3. Update font-awesome to 5.8.1
4. Update jquery to 3.4.0
5. Fix Messed Layout
6. Code Formatted

**Messed layout**
Screenshot from 2019-04-14 09-25-36

**Corrected layout**
Screenshot from 2019-04-14 09-31-36

### CODE REVIEW

**Comment by chankruze** [comment]
@Syknapse check now !

**Comment by Syknapse** [comment]
@chankruze Your PR has been accepted and merged. Thanks a lot for this great contribution. It is always great to see someone going above and beyond and making the project better. This is the essence of what this project is about.

**Comment by Syknapse** [comment]
If I can give you one piece of advice, I didn't like much the "I'm not like the rest of them" comment. Most people who contribute to this project are doing their very first contribution and it gives them the confidence to contribute more in the future.
Your work speaks for itself, you really did improve the project and that is a testament on its own.

**Comment by chankruze** [comment]
I write that for a reason, that's definitely not to be offended, what i saw in your project is, you merged some PR's in which, the project got messed up (that layout).
- 3 guys added code below template, so i added thinking that the edited template but in diff i show template is above. You could have asked them to correct that before merging.
- 2 guys copy paste the template but didn't edit that comment as their card. It that is fine then we shouldn't have comments in first lace.
- 2 guys added their code inside others card which messed the entire layout.

If we shouldn't ask them to correct these things, review again after creating PR we are creating bad contributors which in future may mess up with lager projects.

That's the points for you and i will also look to say things in more simplified & polite ways.
Have a nice day !

**Pull request merged**
