### PR TITLE
Prathamesh's card

### PR DESCRIPTION
**Pull request by Pratham82**
Added my card information

### CODE REVIEW

**Comment by Syknapse** [comment]
Hey @Pratham82 just curious why did you close this PR?

**Comment by Pratham82** [comment]
There was a merge conflict even though I've added the card at the end, I didn't understand exactly what was the issue so that's why I closed it

**Comment by Syknapse** [comment]
Give it another shot. It's normal to get conflicts when lots of other people are adding their cards at the same time to the same line. Between the time you fork the project and the time we attempt to merge it several new cards would have been added. Submit your card and don't worry, if it's simply a conflict caused by placement then we will resolve it as we merge :)

**Comment by Pratham82** [comment]
Okay I'll try again thanks for your help

**Pull request closed without merging**
