### PR TITLE
card hover, border, shadow style change

### PR DESCRIPTION
**Pull request by Hasib24**

### CODE REVIEW

**Review by nzaih1999 — COMMENTED** [review]
Hello @Hasib24 thanks for your contribution. Would you please send us some screenshots of how the styles look in your local file? Because we can't see the styles here

**Comment by Hasib24** [comment]
Here  is the hover effect screen shot..on hover a card move -5px on y axis. I also changed the border from black to white 
Screenshot_2

**Comment by nzaih1999** [comment]
This looks pretty neat.. thanks you so much for your contribution..let me merge it. happy coding amigo!

**Review by nzaih1999 — APPROVED** [review]

**Comment by Hasib24** [comment]
Thank you for receiving my code. I thought you would not reply. I am very excited because this is first contribution of my codinglife.

**Pull request merged**
