### PR TITLE
kdipto1 card

### PR DESCRIPTION
**Pull request by kdipto1**

### CODE REVIEW

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@kdipto1, Kindly add 3 resources that can help fellow developers.

**Comment by kdipto1** [comment]
3 resources are added

**Comment by kdipto1** [comment]
> @kdipto1, Kindly add 3 resources that can help fellow developers.

I added 3 resources.

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@kdipto1, Congratulation on your PR Merge, and Thanks for your Contribution. You can check your card in our [Live Website](https://syknapse.github.io/Contribute-To-This-Project/)! It may take 2-3 minutes to make your card visible in our website. 

Welcome to Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Pull request merged**
