### PR TITLE
Vraj's card

### PR DESCRIPTION
**Pull request by Vrajp08**
Added my card to the index.html

### CODE REVIEW

**Comment by TenTraicion** [comment]
@Vrajp08, It seems like you changed too many codes. Kindly undo those changes and add just you card alone on top of the card section. Thanks!

**Review by TenTraicion — CHANGES_REQUESTED** [review]
undo the changes and add your card on the top of the card section

**Comment by Vrajp08** [comment]
I already added my card on the top of the card section

**Comment by CandidDeer** [comment]
Hi Vraj, thank you for resolving the change request. I have merged your card to the master file now. It will be live in a couple of minutes. ✨ Good job!

**Pull request merged**
