### PR TITLE
Added card of Dhruvin #2329

### PR DESCRIPTION
**Pull request by djv03**
This is my PR for added card

### CODE REVIEW

**Comment by CandidDeer** [comment]
@Syknapse Please review the general enhancement of HINDI.md and README.md and check for feasibility to merge. Thx.

**Review by Syknapse — APPROVED** [review]
Thank you for the great contribution and making the readme available to more people. We appreciate it!

**Comment by Syknapse** [comment]
> @Syknapse Please review the general enhancement of HINDI.md and README.md and check for feasibility to merge. Thx. FYI: card in index.html is fine.

@CandidDeer This looks good to me and can be merged 🚀

**Comment by CandidDeer** [comment]
Thank you, merged! 👍🏻

**Comment by djv03** [comment]
feeling great on being merged in to main branch(both me and my commits! ).
Is there anything else you can suggest me to do on this in open source world???

**Pull request merged**
