### PR TITLE
Update contact section of Anu's Card

### PR DESCRIPTION
**Pull request by anu-codes**
Made some tweaks to correct the display of my contact information.
1. Github icon was missing
2. Contact information was separated in two paragraph tags

Apologies for the mistake and I hope that my card can get updated!

image

### CODE REVIEW

**Comment by Preet-Sojitra** [comment]
Your card will get updated, but before that please remove those two comments which are above your card (line number 142 and 143)
Remove those and commit your changes, we will merge your card.

Adding image for your reference:
image

**Comment by anu-codes** [comment]
@Preet-Sojitra Thank you for your help, I have removed the comments now.

**Comment by Preet-Sojitra** [comment]
Congratatulations @anu-codes merged your pull request 🥳 . Have a nice day

**Comment by anu-codes** [comment]
Thank you for your patience and help @Preet-Sojitra !!

**Pull request merged**
