### PR TITLE
Obitotski card

### PR DESCRIPTION
**Pull request by Obitotski**
Added a new card with my info

### CODE REVIEW

**Review by dilshankarunarathne — COMMENTED** [review]
Hello @Obitotski, your code seems okay but it looks like your code is not indented correctly.

**Comment by Obitotski** [comment]
> Hello @Obitotski, your code seems okay but it looks like your code is not indented correctly.

Thank you @dilshankarunarathne. I`ve fixed indents.

**Comment by dilshankarunarathne** [comment]
Great! 🎉❤ @Obitotski,
Your code looks good, we will merge your pull request ASAP.

**Comment by Obitotski** [comment]
Thank you!😊

**Comment by dilshankarunarathne** [comment]
Congratulations 🎉❤
Your pull request was merged.

**Pull request merged**
