### PR TITLE
HJ's card

### PR DESCRIPTION
**Pull request by johnlew01**

### CODE REVIEW

**Review by cesarcuadro — APPROVED** [review]
Good Job!

**Review by nzaih1999 — APPROVED** [review]

**Comment by CandidDeer** [comment]
@nzaih1999 and @cesarcuadro I can see you have approved the PR, but not merged it. Do you need help with resolving the merge conflicts? Or is there some other reason you are waiting to merge? Please let me know and I'll be happy to help. 👍

**Comment by cesarcuadro** [comment]
I tried merging the pr, but I wasn’t able to resolve the conflict. It seemed like it was on a branch of a branch and couldn’t connect to main.

**Comment by CandidDeer** [comment]
@cesarcuadro I see. I fixed the merge conflicts for you and merged into master. 👍🏻 I find that if there are multiple issues, it is easier to open the current, live index.html in VS code and add the PR content's card manually. Then you can easily resolve the conflict. LEt me know if you have any questions about this.

@johnlew01 Thank you for your contribution. It has been merged into our website and your card is live now. Good job! ✨

**Pull request merged**
