### PR TITLE
Add my Card Information

### PR DESCRIPTION
**Pull request by Arcee69**

### CODE REVIEW

**Review by lax0248917 — APPROVED** [review]
Hello @Arcee69, this all looks great. Thank you for contributing. Will get your PR merged soon. Best of luck with open source in the future. Take care 🚀

**Review by lax0248917 — CHANGES_REQUESTED** [review]
Sorry @Arcee69 for the confusion. Looking closer I noticed that you added your card to the end of the list, you will want to make a change and move your code to just below this line here
image
Collins' card starting point is a good example. Make that change and push your commit to the same branch and PR and we will get your card added. Let me know if you have any questions.

**Review by Arcee69 — COMMENTED** [review]
I have made the changes you requested

**Comment by lax0248917** [comment]
> I have made the changes you requested

Hi @Arcee69 did you push those changes to the main branch on Acree69/Contribute-To-This-Project? I am not seeing them here.

**Comment by lax0248917** [comment]
Hello @Arcee69, thank you for making those changes. We merged your Pull Request 🎉  Best of luck with open source in the future 🚀

**Pull request merged**
