### PR TITLE
Tim David Harris's Card

### PR DESCRIPTION
**Pull request by timdavidharris**
creating my card for this open source project

### CODE REVIEW

**Comment by timdavidharris** [comment]
I do not understand what the specific issue is. Can someone please help me understand what changes I need to make? Thanks!

**Comment by lax0248917** [comment]
HI TIm! Thank you for contributing. Sorry for the delay, we are getting backed up with Pull Requests but working hard to get them taken care of. Appreciate your patience. In your comment regarding "specific issues", did someone send you a request for a change in your submission?

**Comment by timdavidharris** [comment]
Screenshot from 2021-07-10 16-07-05
I was referring to the message I was seeing here (see included image).

**Comment by lax0248917** [comment]
Ahh gotcha, yeah basically this is pointing out a merge conflict. This is normally due to the merge of code in the same spot you wrote yours. Not a problem. We as maintainers will review the code and resolve the merge conflicts to close out the pull request. We will get yours taken care of. Thank you for pointing it out. 😁

**Comment by lax0248917** [comment]
Thanks for contributing Tim. We were able to merge your Pull Request 🎉  Best of luck in the future with your journey in coding. Take care 🚀

**Pull request merged**
