### PR TITLE
Aditya Naresh Card added

### PR DESCRIPTION
**Pull request by Aditya-Naresh**
@CandidDeer . Think the change wasn't updated fork in #2505 . Hope this one is fine. Please check and advice. 

Thank you

### CODE REVIEW

**Comment by Aditya-Naresh** [comment]
@Syknapse

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please move your card to start in line 117. Everything else is okay.

**Comment by Aditya-Naresh** [comment]
@CandidDeer done

**Comment by CandidDeer** [comment]
Thanks for making the changes. Well done. I've merged your PR and your card will be live in a moment.

**Comment by Aditya-Naresh** [comment]
Thank you @CandidDeer

**Pull request merged**
