### PR TITLE
Feature/prettier ci setup

### PR DESCRIPTION
**Pull request by lax0248917**
These commits add the necessary folders and configuration file to run a Prettier Continuous Integration check on code submissions. 🚀

### CODE REVIEW

**Comment by AdityaSharma911** [comment]
@Syknapse Do we need this enhancement?

**Review by AdityaSharma911 — COMMENTED** [review]
Merge code checked

**Comment by Syknapse** [comment]
> @Syknapse Do we need this enhancement?
> 

I will checkout this PR soon and see how it works. It could be very useful.

**Review by Syknapse — APPROVED** [review]
If you have tested it and seen it works I am happy for you to merge this into master. Go ahead.
If it reduces the number of conflicts we get with style issues then it would be the best enhancement we've made to the project in a while. 
I will be looking forward to monitoring the results.

**Pull request merged**
