### PR TITLE
change btn styles

### PR DESCRIPTION
**Pull request by ImanHasan**

### CODE REVIEW

**Review by nzaih1999 — COMMENTED** [review]
Hello @ImanHasan thanks for your contribution. Please provide an image comparing the 2 buttons. Thanks

**Comment by ImanHasan** [comment]
sure
Screenshot from 2022-10-05 13-44-15
Screenshot from 2022-11-15 12-14-53

**Comment by ImanHasan** [comment]
> Hello @ImanHasan thanks for your contribution. Please provide an image comparing the 2 buttons. Thanks

Sure
Screenshot from 2022-11-15 12-14-53
Screenshot from 2022-11-15 12-14-15

**Comment by ImanHasan** [comment]
Sure
Before

Screenshot from 2022-11-15 12-14-15

After

Screenshot from 2022-11-15 12-14-53

**Comment by ImanHasan** [comment]
Sure

Before doing change it was not prominent on screen and having a white background and it was not seems like button it was seems like a paragraph.

Screenshot from 2022-11-15 12-14-15

After doing change it become prominent and also matches the theme of page with yellowish background and now it seems like a perfect button.

Screenshot from 2022-11-15 12-14-53

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@ImanHasan, That's a good addition and thanks for noticing and contributing on that matter. But I think a color that goes well with both light and dark theme of our project would be better. The yellowish tone is good for dark theme but not for the light one. Kindly change the color according to the theme, you can choose different color for different theme too.

**Comment by TenTraicion** [comment]
for any kind of query you can ask here or in our [Discord Community: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF)

**Comment by ImanHasan** [comment]
You are absolutely right and thank you so much for good advice and considering my advice. But we can change the border color for prominent rather then background color if you want.

**Comment by TenTraicion** [comment]
@ImanHasan, make it soothing for eye. It will be much appreciated.

**Comment by TenTraicion** [comment]
That seems good, lets see what others say. 
@CandidDeer @Syknapse @win21H2

**Review by TenTraicion — APPROVED** [review]

**Review by Syknapse — APPROVED** [review]
Ok, I see the change and it looks good. I'm happy the discussion lead to adopting the gradient which matches the rest of the page. Great contribution and review process. Well done everyone. 
I'm approving this for merging but if @ImanHasan can remove the commented out code from the CSS file before we merge it that would be great. We no longer need the old code and it's better to remove any code we don't use.

**Comment by ImanHasan** [comment]
Thank you so much i am very happy to contribute with your project

**Comment by TenTraicion** [comment]
@ImanHasan, Your PR is waiting a final change: remove the commented out code from the CSS file
we will merge after making the requested change. Thanks!

**Comment by ImanHasan** [comment]
I did all the changes i was facing some issues in previous branch so that's why i made again branch and send you the pull request please accept and can merge my changes. I am really happy to contribute with you. Thank you.

**Pull request closed without merging**
