### PR TITLE
Fixed Spelling mistake of some Bangla words

### PR DESCRIPTION
**Pull request by alrakib1**
Fixed spelling mistake on some Bangla words on readme file and also added comments on the starting and ending of my card info in index.html file.

### CODE REVIEW

**Review by TenTraicion — CHANGES_REQUESTED** [review]
@alrakib1 Thanks for the fixes. Kindly undo the changes in index.html file and we are good to go.

**Comment by alrakib1** [comment]
basically I didn't changed anything on the index.html file. I just put comments on the card that I had created yesterday. I had forgotten to add comments before and after my card's end. So, should I remove them ??

**Comment by alrakib1** [comment]
@TenTraicion 


        <div class="card">
          <p class="name">Your name</p>
          <p class="contact">
            <i class="fab fa-x-twitter"></i>
            <a href="https://www.twitter.com" target="_blank">Your handle</a>
            <i class="fab fa-github"></i>
            <a href="https://www.github.com" target="_blank">Your handle</a>
          </p>
          <p class="about">about you</p>
          <div class="resources">
            <p>3 Useful Dev Resources</p>
            <ul>
              <li>
                <a href="#" target="_blank" title="First Resource">Resource 1</a>
              </li>
              <li>
                <a href="#" target="_blank" title="Second Resource">Resource 2</a>
              </li>
              <li>
                <a href="#" target="_blank" title="Third resource">Resource 3</a>
              </li>
            </ul>
          </div>
        </div>
        

        
        
        

        
        
        
        
        
        I didn't remove instructions comment  from the index.html.
        
       Basically,  I mistakenly added  comment after          comment and then started writing my card which I suppose isn't correct. So, I choose to edit it and fixed the mistakes that I had made.

**Review by TenTraicion — APPROVED** [review]

**Comment by TenTraicion** [comment]
@alrakib1, Congratulations on your PR Merge, and Thanks for your Contribution. Welcome to the Open Source Community. You can follow the [Next Steps](https://github.com/Syknapse/Contribute-To-This-Project#next-steps) now. You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by alrakib1** [comment]
Thank you

**Pull request merged**
