### PR TITLE
Kuba card

### PR DESCRIPTION
**Pull request by popunusog**
Adding my card

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Your PR is making changes to workspace.xml. please explain why. Thx.

**Comment by ascodeasice** [comment]
@CandidDeer I think that's file auto-generated by Intellij IDEA, we should update our `.gitignore`

**Comment by CandidDeer** [comment]
> @CandidDeer I think that's file auto-generated by Intellij IDEA, we should update our `.gitignore`

I see. I've added .idea/workspace.xml to our .gitignore. But how come it is not visible in the PR that workspace.xml won't be merged if I merge this PR? Thx!

**Comment by ascodeasice** [comment]
Thank you for your contribution

**Pull request merged**
