### PR TITLE
Anagh's Card

### PR DESCRIPTION
**Pull request by anagh9**
Added card with my Information below Contributor's card.

### CODE REVIEW

**Review by chrisharris333 — DISMISSED** [review]

**Review by chrisharris333 — CHANGES_REQUESTED** [review]
Please add one line of blank space between your card and the next, and re-push those changes.

**Review by chrisharris333 — CHANGES_REQUESTED** [review]
I hate to do this to you Anagh, but only one blank line is needed.  Get that fixed up, push again, and I'll approve.

**Comment by chrisharris333** [comment]
@anagh9 -If you do a pull before fixing the extra line that might correct the conflicts.

Thanks.

**Review by chrisharris333 — APPROVED** [review]
Looks good to me.  Approving.

**Review by Prajwalprakash3722 — APPROVED** [review]

**Pull request merged**
