### PR TITLE
Add my card information

### PR DESCRIPTION
**Pull request by iathul**

### CODE REVIEW

**Review by iatharva — CHANGES_REQUESTED** [review]
Looks like you have added your card at the end of the file, you have to add your card just below the template as per instructions given in step 5, you can check it [here](https://github.com/Syknapse/Contribute-To-This-Project/).
Once the changes are done, We'll review the PR and merge it.

**Comment by iathul** [comment]
@iatharva  updated the pull request

**Comment by iatharva** [comment]
Still, not at the top, go to line 117 then press enter and paste the card there.

**Comment by iathul** [comment]
@iatharva Updated the changes

**Comment by iatharva** [comment]
Thank you for the contribution and welcome to open source!

**Pull request merged**
