### PR TITLE
Update the readme docs and fix links error

### PR DESCRIPTION
**Pull request by ThesllaDev**

### CODE REVIEW

**Comment by lax0248917** [comment]
Thank you @ThesllaDev for your continued contribution. 👍 

@Syknapse first file looks good, decision rests with you if you want it as "Collobartors" or "Maintainers". I don't speak or read Portuguese so I'll leave that review up to whoever is qualified 😄. If this is approved I can make sure it gets merged.

Take care 🚀

**Comment by Syknapse** [comment]
Yeah I did change it from collaborators to maintainers to avoid confusion with "contributors". We should use contributors for the users who contribute code and maintainers for those who review and merge PRs.

**Comment by lax0248917** [comment]
> Yeah I did change it from collaborators to maintainers to avoid confusion with "contributors". We should use contributors for the users who contribute code and maintainers for those who review and merge PRs.

@Syknapse I think this is best as well. Awaiting your review approval and we will get this merged. 🦾

**Review by Syknapse — APPROVED** [review]

**Comment by Syknapse** [comment]
@lax0248917 approved, all yours 👍🏼

**Comment by lax0248917** [comment]
@ThesllaDev, Thank you so much for updating the documentation for readability and consistency. Also appreciate you monitoring and making the necessary edits to the Portuguese languages files. This is what "Open Source" is all about 👏  👏

**Comment by ThesllaDev** [comment]
> 
> 
> @ThesllaDev, Thank you so much for updating the documentation for readability and consistency. Also appreciate you monitoring and making the necessary edits to the Portuguese languages files. This is what "Open Source" is all about 👏 👏

@lax0248917 thanks for the great project to introduce open source, that's it, open source is all good!

**Pull request merged**
