### PR TITLE
revised MAIN README

### PR DESCRIPTION
**Pull request by win21H2**
This PR will have details for a revised version of the MAIN README file

### CODE REVIEW

**Comment by win21H2** [comment]
Closing PR because I dont have enough time to work on it right now

**Comment by Syknapse** [comment]
I have reopened this PR because it is a very useful improvement to our readme, there was only two very small changes to make before we can merge it. Any of the maintainers can take it on and do it if you don't have time and we can still beneft form this improvement.

**Comment by win21H2** [comment]
Will work on it over the next few days if needed

**Comment by Syknapse** [comment]
Hey, before you do check the current readme because it has been changed since this was open. If you see opportunities to improve it further then that would be great

**Comment by win21H2** [comment]
Will close this PR as it's working on a branch that's outdated and I'm too lazy to re-update it. I will open a new PR if I feel there is a design change that is needed!

**Pull request closed without merging**
