### PR TITLE
Chantae's card 

### PR DESCRIPTION
**Pull request by taepal467**
Added my card to the index.html file.

### CODE REVIEW

**Comment by taepal467** [comment]
Hello, sorry about that. I have made the changes requested. Also, will I have to make a new pull request? Sorry, I'm still learning how to participate in open source projects and how to use Github.

**Comment by iatharva** [comment]
It's alright, I am glad you are learning and figuring it out. 
About the question which you asked there is no need for the new PR (Pull Request), cause whenever you make changes in your repository and there is PR open from your repository to another, the changes will be automatically reflected in the PR. As you can see the commit which you did recently in PR itself.

**Comment by iatharva** [comment]
Thanks for the contribution, and Hope you have a great journey ahead in open-source 💯 . Feel free to reach me if you need any help with git or Github.

**Comment by taepal467** [comment]
> Thank you for the contribution, and Hope you have a great journey ahead in open-source 💯 . Feel free to reach me if you need any help with git or Github.

Thank you so much. And I really enjoyed this project by the way.

**Pull request merged**
