### PR TITLE
Oluwatimilehin Esan's Card

### PR DESCRIPTION
**Pull request by therealtmmy**
Added a new card and modify the content with my info.

### CODE REVIEW

**Review by Michaelin007 — CHANGES_REQUESTED** [review]
I think you don't need <br>

**Comment by therealtmmy** [comment]
> 

You don't need what? Would you please expantiate better. Thank you

**Comment by Michaelin007** [comment]
> > 
> 
> You don't need what? Would you please expantiate better. Thank you

Sorry my first statement isn't complete "<br>"

**Comment by therealtmmy** [comment]
> > > 
> > 
> > 
> > You don't need what? Would you please expantiate better. Thank you
> 
> Sorry my first statement isn't complete "" the line break in your short description

Alright.

**Review by TenTraicion — APPROVED** [review]

**Pull request merged**
