### PR TITLE
prashant commit

### PR DESCRIPTION
**Pull request by prashantkumarsahu**

### CODE REVIEW

**Review by CandidDeer — CHANGES_REQUESTED** [review]
Please add 2nd and 3rd resources, then I will be happy to merge. Thx.

**Comment by CandidDeer** [comment]
Please note that we will be closing PRs 7 days after initial opening if any change requests have not been fulfilled by then. Please reach out if you need help with this. Thx.

**Comment by prashantkumarsahu** [comment]
Added 2nd and 3rd resource as well.

**Comment by CandidDeer** [comment]
Thank you for your contribution and making the requested changes. I have merged your PR and your card will be live in a moment.

**Pull request merged**
