### PR TITLE
Card add

### PR DESCRIPTION
**Pull request by Shekhar-Dangi**

### CODE REVIEW

**Review by SayuruRehan — COMMENTED** [review]
👍

**Review by Preet-Sojitra — APPROVED** [review]
Looks great 👍 . Your pull request will be merged soon

**Comment by Shekhar-Dangi** [comment]
@Preet-Sojitra Ok bro!

**Comment by Preet-Sojitra** [comment]
Congratulation @Shekhar-Dangi for your first contribution to open source. Your pull request has been merged. You can view your card on [project's website](https://syknapse.github.io/Contribute-To-This-Project/). Have a great day ahead :)

**Comment by Shekhar-Dangi** [comment]
Thank you @Preet-Sojitra .

**Pull request merged**
