### PR TITLE
Fixed dark view toggle and search bar when focused

### PR DESCRIPTION
**Pull request by alisha-takkar**

### CODE REVIEW

**Comment by alisha-takkar** [comment]
#2091

**Comment by TenTraicion** [comment]
@alisha-takkar, could you provide us some ss of your end. 
@Syknapse asking for a review...

**Comment by alisha-takkar** [comment]
Sure 

image

**Review by Syknapse — APPROVED** [review]
This is an excellent contribution. Thank you for fixing the bug, and a great solution you gave it. And thanks for enhancing the search style. 
Note for the future, if you notice your code style settings have caused large changes to a file (in this case adding the ; and changing ' to ") it would be a good idea to disable it before you commit, so only the changes you need are in the commit. 
But overall great contribution. Thanks

**Pull request merged**
