### PR TITLE
Augustine's Card

### PR DESCRIPTION
**Pull request by acalvino4**
added a new card with my info

### CODE REVIEW

**Comment by Syknapse** [comment]
@acalvino4 hey, I cannot merge this PR because the repository you are merging from is `unknown`, so it's maybe a private repository or you have already deleted it. You'll need to start again, please. Thanks for your contribution and I will be waiting for the new PR.

**Comment by acalvino4** [comment]
I made the request a couple months ago, but after seeing nothing happen for
so long,I just deleted it a couple days ago.

**Comment by Syknapse** [comment]
Oh I'm sorry to hear that. I have been swamped with PRs while being very busy at work too, I fell really behind. I apologise for this. I'm finally back on track and I can merge regularly again. If you still think this is a useful thing for you to do it would be great to see a new PR. Thanks a lot

**Comment by acalvino4** [comment]
Appreciate it. I think I learned through the process though, so wasn’t for
naught!

**Pull request closed without merging**
